Shared Regs functional with test programs
BrandonShockley/Decontainment pull request #1
Opened 2020-02-09 21:18 UTC by ThomasSeaver

Altered VirtualMachine.cs to extend reg num, add propagation call to data manipulation instructions, and add method to update shared regs from within vm

Altered BotManager.cs to add coroutine that, after a delay, uses the method in bot.VM to update shared regs across teams

Added SharedRegisters and SharedRegisters2 as testing programs that demonstrate the bots waiting for eachother to update the regs. You can examine the programs yourself, but they basically are taking turns changing the reg and then waiting for their partner to change the reg, moving each time they set a reg for visual clarity.

I did not edit the editor's display of regs since that is probably something we should discuss beforehand and the system extends to 10 regs automatically via the numreg change. 

I exposed the propagation delay variable in the inspector, but the coroutine seems to use the first value in the variable even after changing it in the inspector? I'm really not sure what's going on there; even after changing it in the inspector, the debug log would report the original value. I'm not even sure it was using the inspector value at all, and I think I would reset to 0 unless I set the delay manually in the awake function. Regardless, the delay functions, the coroutine just doesn't seem to want to use any updated version of the variable, and I'm not sure what part of C# I'm running up against there.

2020-02-10 00:40 UTC, BrandonShockley requested changes

2020-02-10 00:40 UTC, BrandonShockley commented on Assets/Decontainment/Singletons/BotManager.cs
> +    public IEnumerator PropagationCoroutine (int registerNumber, int registerValue, int botTeamID) {
```suggestion
    public IEnumerator PropagationCoroutine(int registerNumber, int registerValue, int botTeamID)
    {
```
Stay consistent with the rest of the codebase

2020-02-10 00:40 UTC, BrandonShockley commented on Assets/Decontainment/Assembly/VirtualMachine.cs
> +    public void updateSharedReg(int registerNumber, int registerValue) {
```suggestion
    public void UpdateSharedReg(int registerNumber, int registerValue)
    {
```
Keep the code style consistent

2020-02-10 00:40 UTC, BrandonShockley commented on Assets/Decontainment/Singletons/BotManager.cs
> +        //Debug.Log("Propagating with delay: " + propagationDelay);
Don't leave commented out code in the PR

2020-02-10 00:40 UTC, BrandonShockley commented on Assets/Decontainment/Singletons/BotManager.cs
> +        yield return new WaitForSecondsRealtime(propagationDelay);
Change this to use WaitForSeconds

2020-02-10 00:40 UTC, BrandonShockley commented on Assets/Decontainment/Assembly/VirtualMachine.cs
> +    public void updateSharedReg(int registerNumber, int registerValue) {
Also this method isn't used anywhere

2020-02-10 00:40 UTC, BrandonShockley commented on Assets/Decontainment/Singletons/BotManager.cs
> +    public float propagationDelay;
Make this a private variable with the `[SerializeField]` attribute

2020-02-10 00:40 UTC, BrandonShockley commented on Assets/Decontainment/Singletons/BotManager.cs
> +    public IEnumerator PropagationCoroutine (int registerNumber, int registerValue, int botTeamID) {
I highly-highly recommend making the coroutine method private and making a `public void PropagateRegister` method that sets up the coroutine for you. That way you don't have to type as much code to do the propagation like you did in the VirtualMachine class.

2020-02-10 00:40 UTC, BrandonShockley commented on Assets/Decontainment/Assembly/VirtualMachine.cs
> +    public const int NUM_REGS = 10;
Do what we discussed in the chat

2020-02-12 18:55 UTC, ThomasSeaver commented
Updated as requested in regards to style, and added new register group to the editor with new color as to visually differentiate. Still functional as before.

2020-02-12 19:30 UTC, BrandonShockley requested changes

2020-02-12 19:30 UTC, BrandonShockley commented on Assets/Decontainment/Singletons/BotManager.cs
> +        propagationDelay = 3.0f;
Remove this

2020-02-12 19:55 UTC, BrandonShockley approved these changes

2020-02-12 19:56 UTC, merged