Shotgun
BrandonShockley/Decontainment pull request #2
Opened 2020-02-14 16:33 UTC by KingArthurClay

About time I got this done.

Currently, the projectile is just copied from the pulse projectile, with the addition of a lifetime. It will need to be changed in a visual pass later (maybe with the next weapon commit). Having ShotgunPellet.cs be a subclass of Pulse.cs would require some permissions to be changed - the lifetime co-routine needs to be started from Init();

Shooter.cs now supports weapons firing multiple projectiles.

Misc. Fixes including recreating the rest of the weapon assets using the new WeaponData asset and creating a new bot config for testing.

2020-02-14 16:35 UTC, KingArthurClay commented
KingNullpointer is just my personal/pseudonymous account

2020-02-14 21:48 UTC, BrandonShockley requested changes

2020-02-14 21:48 UTC, BrandonShockley commented on Assets/Decontainment/Bot/Weapons/Projectiles/Scripts/ShotgunPellet.cs
> +    private IEnumerator deathTimer()
Method names should use CapitalCamelCase
See the style guide

2020-02-14 21:48 UTC, BrandonShockley commented on Assets/Decontainment/Bot/Weapons/Projectiles/Scripts/ShotgunPellet.cs
> +        if (c.gameObject != shooter.gameObject)
Fix the bracket style (do this for all your if statements, for loops, etc.)

2020-02-14 21:48 UTC, BrandonShockley commented on Assets/Decontainment/Bot/Scripts/Shooter.cs
> +                    float offset = Mathf.Ceil(((float)weaponData.numShots) / 2.0f - weaponData.numShots);
Do the thing we talked about for this

2020-02-15 03:52 UTC, BrandonShockley requested changes

2020-02-15 03:52 UTC, BrandonShockley commented on Assets/Decontainment/Bot/Weapons/Projectiles/Scripts/ShotgunPellet.cs
> +        if (c.gameObject != shooter.gameObject)
Fix bracket

2020-02-15 03:52 UTC, BrandonShockley commented on Assets/Decontainment/Bot/Weapons/Projectiles/Scripts/ShotgunPellet.cs
> +            if (c.TryGetComponent<Health>(out Health health))
Fix bracket

2020-02-15 03:52 UTC, BrandonShockley commented on Assets/Decontainment/Bot/Weapons/Projectiles/Scripts/ShotgunPellet.cs
> +                health.TakeDamage(1);
Move this damage value into an inspector editable variable

2020-02-15 03:52 UTC, BrandonShockley commented on Assets/Decontainment/Bot/Weapons/Projectiles/Scripts/ShotgunPellet.cs
> +    private float lifeTimer;
Give `lifeTimer` a default value. Otherwise this annoying warning shows up in the log every time the code compiles.

2020-02-15 03:52 UTC, BrandonShockley commented on Assets/Decontainment/Bot/Weapons/Projectiles/Scripts/ShotgunPellet.cs
> +public class ShotgunPellet : Projectile {
Fix bracket

2020-02-15 21:51 UTC, merged